---
stages:
  - test

testing:
    image: python:3.8
    stage: test
    script:
      - pip install -r requirements/test.txt
      - black . --check
      - isort -rc -c
      - flake8 .
      - mypy -p nwastdlib
      - pytest
    tags:
      - python-lint-ext
