---
stages:
  - lint

lint check:
    image: python:3.6
    stage: lint
    script:
      - pip install flake8 --quiet
      - flake8
      - python setup.py check
      - python setup.py test
    tags:
      - python-lint-ext
