---
stages:
  - lint

lint check:
    image: python:3.7
    stage: lint
    script:
      - pip install flake8 flake8-mypy --quiet
      - flake8
      - mypy -p nwastdlib
      - python setup.py check
      - python setup.py test
    tags:
      - python-lint-ext
